version: "3"

services:
  chat:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/mmeowmeow/simple-web-chat:master
    container_name: backend
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
