name: my-app-workflow

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/**'
      - '.github/workflows/app-workflow.yaml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/**'
      - '.github/workflows/app-workflow.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify
